-- ── Table ────────────────────────────────────────────────
create table movies (
  id          bigint generated by default as identity primary key,
  title       text not null,
  release     int2,
  content     text,
  image_url   text,
  embedding   extensions.vector(1536)
);

-- ── Index for fast vector search ─────────────────────────
create index on movies
using ivfflat (embedding extensions.vector_cosine_ops)
with (lists = 100);

-- ── Match function ────────────────────────────────────────
create or replace function match_choices (
  query_embedding extensions.vector(1536),
  match_threshold float,
  match_count     int
)
returns table (
  id          bigint,
  title       text,
  content     text,
  image_url   text,
  similarity  float
)
language sql
as $$
  select
    movies.id,
    movies.title,
    movies.content,
    movies.image_url,
    (1 - (movies.embedding <=> query_embedding)) as similarity
  from movies
  where (1 - (movies.embedding <=> query_embedding)) > match_threshold
  order by movies.embedding <=> query_embedding asc
  limit least(match_count, 200);
$$;